targets:
  $default:
    builders:
      drift_dev:
        options:
          store_date_time_values_as_text: true
      freezed:
        options:
          format: false

      json_serializable:
        options:
          checked: false
          field_rename: snake
        generate_for:
          exclude:
            - lib/data/database/tables/**.dart
