class SyncTableDefinition {
  final String name;
  final List<String> dataColumns;

  const SyncTableDefinition(this.name, this.dataColumns);
}

const syncableTableDefinitions = [
  SyncTableDefinition('users', [
    'id',
    'email',
    'display_name',
    'currency_code',
    'locale',
    'timezone',
    'ai_enabled',
    'created_at',
    'updated_at',
    'deleted_at',
  ]),
  SyncTableDefinition('households', [
    'id',
    'name',
    'created_by_user_id',
    'created_at',
    'updated_at',
    'deleted_at',
  ]),
  SyncTableDefinition('household_members', [
    'id',
    'household_id',
    'user_id',
    'role',
    'created_at',
    'updated_at',
    'deleted_at',
  ]),
  SyncTableDefinition('accounts', [
    'id',
    'household_id',
    'owner_user_id',
    'name',
    'account_type',
    'balance',
    'currency_code',
    'is_archived',
    'is_hidden',
    'created_at',
    'updated_at',
    'deleted_at',
  ]),
  SyncTableDefinition('transactions', [
    'id',
    'account_id',
    'category_id',
    'payee_id',
    'parent_transaction_id',
    'recurring_template_id',
    'amount',
    'transaction_direction',
    'transaction_mode',
    'transaction_subtype',
    'note',
    'metadata',
    'occurred_at',
    'created_at',
    'updated_at',
    'deleted_at',
  ]),
  SyncTableDefinition('transfers', [
    'id',
    'source_account_id',
    'destination_account_id',
    'amount',
    'fee_amount',
    'note',
    'occurred_at',
    'created_at',
    'updated_at',
    'deleted_at',
  ]),
  SyncTableDefinition('categories', [
    'id',
    'parent_category_id',
    'name',
    'icon',
    'color',
    'category_group',
    'created_at',
    'updated_at',
    'deleted_at',
  ]),
  SyncTableDefinition('payees', [
    'id',
    'normalized_name',
    'display_name',
    'logo_url',
    'created_at',
    'updated_at',
    'deleted_at',
  ]),
  SyncTableDefinition('budgets', [
    'id',
    'household_id',
    'owner_user_id',
    'category_id',
    'amount',
    'month',
    'year',
    'created_at',
    'updated_at',
    'deleted_at',
  ]),
  SyncTableDefinition('debt_records', [
    'id',
    'owner_user_id',
    'counterparty_name',
    'debt_direction',
    'amount',
    'remaining_balance',
    'note',
    'due_date',
    'status',
    'created_at',
    'updated_at',
    'deleted_at',
  ]),
  SyncTableDefinition('goals', [
    'id',
    'owner_user_id',
    'household_id',
    'name',
    'goal_type',
    'target_amount',
    'current_amount',
    'target_date',
    'created_at',
    'updated_at',
    'deleted_at',
  ]),
  SyncTableDefinition('recurring_templates', [
    'id',
    'account_id',
    'category_id',
    'payee_id',
    'amount',
    'recurrence_rule',
    'reminder_enabled',
    'auto_create_disabled',
    'next_occurrence_at',
    'created_at',
    'updated_at',
    'deleted_at',
  ]),
];

final syncableTableNames =
    syncableTableDefinitions.map((t) => t.name).toSet();
